services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 5432:5432

  odoo:
    # FOR BUILDING THE IMAGE USE THIS
    # image: dudanogueira/discuss_hub_cloud
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on:
      - db
    tty: true
    command: odoo -d odoo -u discuss_hub -i discuss_hub #--log-handler :DEBUG
    environment:
      - RUNNING_ENV=prod
      - ODOO_RC=/etc/odoo/odoo.conf
      - HOST=db
      - USER=admin
      - PASSWORD=admin
      - ADMIN_PASSWORD=admin
      - SMTP_SERVER=mailpit
      - SMTP_PORT=1025
      - DISCUSS_HUB_INTERNAL_HOST=http://odoo:8069
      - DISCUSS_HUB_EVOLUTION_URL=http://evolution:8080
      - DISCUSS_HUB_EVOLUTION_APIKEY=1369429683C4C977415CAAFCCE10F7D57E11
      - ODOO_LOGGING_JSON=1
      # store session data in database
      # - SESSION_DB_URI=postgresql://admin:admin@db:5432/odoo
      - ODOO_SESSION_REDIS=1
      - ODOO_SESSION_REDIS_HOST=redis
      #- ODOO_SESSION_REDIS_PASSWORD
      - ODOO_SESSION_REDIS_PREFIX=discusshub-odoo-prod
      - ODOO_SESSION_REDIS_SSL=false
    volumes:
      - ./discuss_hub/:/mnt/extra-addons/discuss_hub
      - odoo_conf:/etc/odoo
      - odoo_data:/var/lib/odoo
    ports:
      - "8069:8069"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  evolution:
    image: evoapicloud/evolution-api:homolog
    restart: always
    depends_on:
      - redis
      - db
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    expose:
      - 8080
    environment:
      - SERVER_URL=http://localhost:8080
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://admin:admin@db:5432/admin?schema=public
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      - DATABASE_SAVE_IS_ON_WHATSAPP=true
      - DATABASE_SAVE_IS_ON_WHATSAPP_DAYS=14
      - DATABASE_DELETE_MESSAGE=true
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/6
      - CACHE_REDIS_TTL=604800
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false
      - CONFIG_SESSION_PHONE_CLIENT=Discuss Hub
      - CONFIG_SESSION_PHONE_NAME=Chrome
      #- CONFIG_SESSION_PHONE_VERSION=2.3000.1020181182
      - AUTHENTICATION_API_KEY=1369429683C4C977415CAAFCCE10F7D57E11
      - WA_BUSINESS_TOKEN_WEBHOOK=evolution
      - WA_BUSINESS_URL=https://graph.facebook.com
      - WA_BUSINESS_VERSION=v21.0
      - WA_BUSINESS_LANGUAGE=pt_BR
      - OPENAI_ENABLED=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mailpit:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-workflows.yaml:/n8n-workflows.yaml
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_RUNNERS_ENABLED=true

  botpress:
    image: botpress/server
    restart: unless-stopped
    command: /botpress/bp
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/botpress
      - REDIS_URL=redis://redis:6379
      - BP_PRODUCTION=true
      - BPFS_STORAGE=database
    depends_on:
      - db
      - redis
    volumes:
      - botpress_data:/botpress/data

  #
  # TYPEBOT
  #

  typebot-builder:
    environment:
      DEBUG: true
      REDIS_URL: redis://redis:6379
      ENCRYPTION_SECRET: do+UspMmB/rewbX2K/rskFmtgGSSZ8Ta
      DATABASE_URL: postgresql://admin:admin@db:5432/typebot
      NODE_OPTIONS: --no-node-snapshot
      NEXTAUTH_URL: http://localhost:8082
      NEXT_PUBLIC_VIEWER_URL: http://localhost:8081
      ADMIN_EMAIL: dudanogueira@gmail.com
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      NEXT_PUBLIC_SMTP_FROM: notifications@typebot.domain.com
      S3_ACCESS_KEY: minio-access-key
      S3_SECRET_KEY: minio-secret-key
      S3_BUCKET: typebot
      S3_ENDPOINT: minio
      S3_SSL: false
    image: baptistearno/typebot-builder:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8082:3000"

  typebot-viewer:
    environment:
      DEBUG: true
      REDIS_URL: redis://redis:6379
      ENCRYPTION_SECRET: do+UspMmB/rewbX2K/rskFmtgGSSZ8Ta
      DATABASE_URL: postgresql://admin:admin@db:5432/typebot
      NODE_OPTIONS: --no-node-snapshot
      NEXTAUTH_URL: "http://localhost:8081"
      NEXT_PUBLIC_VIEWER_URL: "http://localhost:8082"
      ADMIN_EMAIL: dudanogueira@gmail.com
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      NEXT_PUBLIC_SMTP_FROM: notifications@typebot.domain.com
      S3_ACCESS_KEY: minio-access-key
      S3_SECRET_KEY: minio-secret-key
      S3_BUCKET: typebot
      S3_ENDPOINT: minio
      S3_SSL: false
    image: baptistearno/typebot-viewer:latest
    ports:
      - "8081:3000"

  #
  # MINIO
  #

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_USERNAME: minio
      MINIO_PASSWORD: minio123
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio-access-key
      MINIO_SECRET_KEY: minio-secret-key
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: |
      /bin/sh -c "
        sleep 10;
        /usr/bin/mc alias set minio http://minio:9000 minio minio123;
        /usr/bin/mc mb --ignore-existing minio/typebot;
        /usr/bin/mc anonymous set public minio/typebot/public;
        exit 0;
      "

volumes:
  db_data:
  odoo_data:
  odoo_conf:
  minio_data:
  evolution_instances:
  redis_data:
  n8n_data:
  botpress_data:
  typebot_data:
