name: Publish Release Package

on:
  release:
    types: [published]

jobs:
  zip-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create separate ZIPs
      run: |
        mkdir -p dist
        for dir in discuss_hub; do
        zip -r "dist/$dir.zip" "$dir"
        done

    - name: List ZIPs created
      run: ls -lh dist

    - name: Upload all ZIPs
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT_RELEASE_UPLOAD }}